#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const esbuild = require("esbuild");

const ROOT = path.resolve(__dirname, "..");
const ENTRY = path.join(ROOT, "src", "main.mjs");
const OUTFILE = path.join(ROOT, "adreplica.js");
const PACKAGE_JSON = path.join(ROOT, "package.json");
const VERSION_TOKEN = "__ADREPLICA_VERSION__";

function readPackageVersion() {
  const pkg = JSON.parse(fs.readFileSync(PACKAGE_JSON, "utf8"));
  if (!pkg.version || typeof pkg.version !== "string") {
    throw new Error("package.json must contain a string version.");
  }
  return pkg.version;
}

async function buildPayload(version) {
  const result = await esbuild.build({
    entryPoints: [ENTRY],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    sourcemap: false,
    legalComments: "none",
    logLevel: "silent",
    write: false,
    banner: {
      js: [
        "// Generated by scripts/build-payload.cjs. Edit src/ instead.",
        `// AdReplica VERSION: "${version}"`,
      ].join("\n"),
    },
  });
  if (!result.outputFiles || result.outputFiles.length !== 1) {
    throw new Error("esbuild did not produce exactly one payload output.");
  }
  const source = result.outputFiles[0].text.replaceAll(VERSION_TOKEN, version);
  const versionPattern = new RegExp(`VERSION:\\s*"${version.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"`);
  if (!versionPattern.test(source)) {
    throw new Error(`Generated payload does not contain VERSION: "${version}".`);
  }
  return source;
}

async function main() {
  const checkOnly = process.argv.includes("--check");
  const version = readPackageVersion();
  const source = await buildPayload(version);

  if (checkOnly) {
    const current = fs.existsSync(OUTFILE) ? fs.readFileSync(OUTFILE, "utf8") : "";
    if (current !== source) {
      throw new Error("adreplica.js is out of date. Run npm run build:payload.");
    }
    console.log(`adreplica.js is up to date for ${version}.`);
    return;
  }

  fs.writeFileSync(OUTFILE, source);
  console.log(`Generated ${path.relative(ROOT, OUTFILE)} for ${version}.`);
}

main().catch((error) => {
  console.error(error?.stack || error?.message || String(error));
  process.exit(1);
});
